# Config for building https://tmt.readthedocs.io/
version: 2
build:
    os: ubuntu-22.04
    tools:
        python: "3"
    # Override RTD's default build commands, install hatch & delegate
    # the rest to our Makefiles.
    commands:
      - cat docs/conf.py
      - pip install hatch
      - make BUILDDIR=$READTHEDOCS_OUTPUT docs
